site_name: Restify Experiment Replication Package
site_url: https://m5c.github.io/RestifyReplicationPackage/
use_directory_urls: false
nav:
    - Welcome: index.md
    - Result Replication: replication.md
    - Recruitment Material: recruitment.md
    - Group Allocation: allocation.md
    - Training / Task Material: material.md
    - Objects (Legacy Apps): objects.md
    - Correctness Analyzer: analyzer.md
    - Observation Data: data.md
    - About: about.md

theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: blinded
    accent: red
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - tables
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

